### ISSUE TITLE
Checkbox keeps state even if save editor is cancelled

### ISSUE THREAD

**Issue by dominic-simplan** [vaadin/grid-renderers-collection-addon#12]
I have a grid which is set to editable.
Using the CheckboxRenderer, I am displaying checkboxes for boolean values.
It is possible to click on a checkbox even if the row is not in edit-mode (i.e. not double-clicked). The checkbox state changes and the edit-mode for the row is automatically activated (okay so far).

However, if I now cancel the edit-mode of the row, the checkbox state is still displayed as changed. I would expect that if the edit mode is cancelled, the checkbox should be reset to its previous state.

If I double-click on a row to activate the edit-mode explicitly, everything is working as expected. The issue only happens if the edit mode is activated implicitly by changing a checkbox without activating the edit-mode beforehand.

**Comment by TatuLund** [comment]
Thanks for noting. I didn't test it much with buffered edit mode, so missed this one. It is easy fix and will be fixed in next version.

**Comment by TatuLund** [comment]
Fixed in version 0.98
