### ISSUE TITLE
CellStyleGenerator is not invoked for editor cells

### ISSUE THREAD

**Issue by inahas** [vaadin/grid-renderers-collection-addon#14]
I have a CheckboxRenderer for a Boolean property in a Grid. I want it to be centered so I added a CellStyleGenerator to add a custom style.

The style is added to "v-grid-cell" elements but not to "v-grid-editor=cells" cells.

**Comment by TatuLund** [comment]
I think this might be upto Grid's normal behavior. CheckboxRenderer is not rendered in edit row, the editor uses the normal edit widget etc. If you think this is a problem or you want to request specific CellStyleGenerator added for Editor as well, then you should open issue concerning this in github.com/vaadin/framework/issues
