### ISSUE TITLE
Rowkeys are getting Updated on LazyLoading

### ISSUE THREAD

**Issue by alok104** [vaadin/grid-renderers-collection-addon#18]
Hi, We have overridden onChange(String rowKey, String columnId, String newValue) method of TextFieldRenderer class. But for each scroll up/down rowKeys are getting changed. Lets say I have scroll down, lazy loading happened and I am scrolling up and changing some value of starting row, this time rowKey has some different value , it supposed to be one again. Do we have any way to retain the row indexes after scroll up/down?

**Comment by TatuLund** [comment]
This behavior is due Escallator, which is recycling the DOM elements of the Grid, while you are scrolling. Thus client side is mot "remembering" the values that are scrolled away.

**Comment by TatuLund** [comment]
Solution proposal 1: Add streaming text change mode to TextField renderer, i.e. emit value change after each character you type.

**Comment by TatuLund** [comment]
Solution proposal 2: Add mode to TextField renderer where value change is emited before it is scrolled away. This might be possible / feasible, but I need to play and test more. I would put this behind API, since I assume this behavior would not be always wanted.

**Comment by TatuLund** [comment]
Versions 2.2.0 & 1.2.0 have now means to tackle the issue.
