### ISSUE TITLE
BooleanSwitchRenderer setReadonly 

### ISSUE THREAD

**Issue by koapost** [vaadin/grid-renderers-collection-addon#22]
I use BooleanSwitchRenderer lie this 
```
records.addColumn(ApplicationRecordDto::getM1)
                .setRenderer(new BooleanSwitchRenderer((dto, value) -> ((ApplicationRecordDto) dto).setM1((Boolean) value)))
                .setCaption("1");
```
And later on I want to make it read only
`
 records.getColumns().subList(1, records.getColumns().size()).forEach(value -> ((BooleanSwitchRenderer)value.getRenderer()).setReadOnly(flag));`

but it doesn't seam to work!

**Comment by TatuLund** [comment]
Yes, I can replicate this issue.

**Comment by TatuLund** [comment]
2.2.1 released in directory
