### ISSUE TITLE
Simple select Rendering fail after filter

### ISSUE THREAD

**Issue by koapost** [vaadin/grid-renderers-collection-addon#24]
After adding a filter in a grid DataProvider the SimpleSelectRender do not render the correct value.

**Comment by TatuLund** [comment]
That sounds pretty strange. There should not be any specific impact with filtering. That happens in data model level, and renderers are and should be generally unaware of any rendering. Also I found this. It is about the different renderer, but it is about last column, and yes filtering. So there is probably something common here.

https://github.com/vaadin/framework/issues/10359

**Comment by koapost** [comment]
I notced somethink else. Consider this senario,

1.  I add a new dto to my DataProvider. The Dto has a field "year" with an empty string as  initial value .
2. A SimpleSelectRender with values 2017,2018,2019.

On initial display we will have the render showing 2017 and the dto underneath  it with value of an empty string. And this is a case were the render is inconsistent to the model.

**Comment by TatuLund** [comment]
That is a case which is not supported, i.e. that value set in data source and value set in selection being different. They must be the same. So in order to work in the case you mentioned, you would need to have empty value also added in set you put into SimpleSelectRenderer.

**Comment by koapost** [comment]
I already did.

**Comment by TatuLund** [comment]
And did it work after that?

**Comment by TatuLund** [comment]
Version 2.2.2 can be found in library. Thanks for noticing this issue.

**Comment by koapost** [comment]
thanx for responding so fast!
