### ISSUE TITLE
Issue with CheckboxRenderer when used with generated columns on a grid

### ISSUE THREAD

**Issue by rpathimela** [vaadin/grid-renderers-collection-addon#26]
Hi,

I am facing issues with CheckboxRenderer in a vaadin 7.7.1 version when used with generated columns on a grid. Source code is as below:

BeanItemContainer<SpinSignal> bic = new BeanItemContainer<>(CustomClass.class);
        GeneratedPropertyContainer container = new GeneratedPropertyContainer(
        		bic);
        setContainerDataSource(container);

 container.addGeneratedProperty("isAccepted", new PropertyValueGenerator<Boolean>() {
			@Override
			public Boolean getValue(Item item, Object itemId, Object propertyId) {
				SpinSignal signal = (SpinSignal) itemId;
				
				return signal.getSignalDescription().getUsed();
			}

			@Override
			public Class<Boolean> getType() {
				return Boolean.class;
			}
		});    

 Column isAcceptedColumn = getColumn("isAccepted");
        isAcceptedColumn.setHeaderCaption("Is Accepted");
        isAcceptedColumn.setRenderer(new CheckboxRenderer());     

But this column is not getting rendered at all in UI and I dont see any errors also. Can you please check and help? I used 1.2.0 version of the add-on.

Best Regards,
Ramesh

**Comment by TatuLund** [comment]
I haven't yet had time to test this myself, but I attempt to do so as soon I can. However I would like to ask couple of questions

1. Did you remember to recompile the widgetset after you added the add-on to your Project?  Knowing how Grid behaves, and how Renderers are used, missing client renderer would manifest exactly like you see. 

2. Does same issue happen with other Renderers too with generated columns? Renderers should be independent of that column is being generated column. Thus if there is an issue, it should happen with all Renderers and issue being probably somewhere else.

**Comment by rpathimela** [comment]
Hi,

Thank you for the reply, adding an add-on first time, didnt know had to compile the widgeset, I did now and tried again but with no luck. Still ther rendering doesn't work. Could you please check?

**Comment by rpathimela** [comment]
I see the generated xml has the RenderersCollectionWidgetSet included...
[AppWidgetset.gwt.xml.txt](https://github.com/vaadin/grid-renderers-collection-addon/files/1542821/AppWidgetset.gwt.xml.txt)

**Comment by TatuLund** [comment]
I tried the following test application, and I can't replicate your issue. The application and the Renderer works correctly.

`package com.example.myapplication;

import java.util.Random;
import javax.servlet.annotation.WebServlet;
import org.vaadin.grid.cellrenderers.editoraware.CheckboxRenderer;
import com.vaadin.annotations.Theme;
import com.vaadin.annotations.VaadinServletConfiguration;
import com.vaadin.data.Item;
import com.vaadin.data.util.GeneratedPropertyContainer;
import com.vaadin.data.util.PropertyValueGenerator;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Grid.Column;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

@Theme("mytheme")
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();


        Grid grid = new Grid();        
        grid.addColumn("string");
        for (int i=0;i<100;i++) {
        	grid.addRow("String "+i);
        }
        
        GeneratedPropertyContainer container = new GeneratedPropertyContainer(grid.getContainerDataSource());
        container.addGeneratedProperty("isAccepted", new PropertyValueGenerator() {
        	@Override
        	public Boolean getValue(Item item, Object itemId, Object propertyId) {
        			Random random = new Random();
        			return random.nextBoolean();
        		}

        		@Override
        		public Class<Boolean> getType() {
        			return Boolean.class;
        		}
        	});    
        grid.addColumn("isAccepted",Boolean.class);
        Column isAcceptedColumn = grid.getColumn("isAccepted");
        isAcceptedColumn.setHeaderCaption("Is Accepted");
        isAcceptedColumn.setRenderer(new CheckboxRenderer());
        grid.setEditorBuffered(false);
        grid.setEditorEnabled(true);
        
        final TextField name = new TextField();
        name.setCaption("Type your name here:");

        Button button = new Button("Click Me");
        button.addClickListener( e -> {
            layout.addComponent(new Label("Thanks " + name.getValue() 
                    + ", it works!"));
        });
        
        layout.addComponents(grid, name, button);
        layout.setMargin(true);
        layout.setSpacing(true);
        
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
`
