### ISSUE TITLE
The label next the check box.

### ISSUE THREAD

**Issue by smsinc** [vaadin/grid-renderers-collection-addon#3]
I need someway to remove the description next to the checkbox.  Currently when you do batch editing and the field is logical, it is displayed as a checkbox with no label.  I would like to duplicate that when the checkbox is just displayed.  In my opinion, having the field label repeat the column label make things more cluttered then they need to be.

**Comment by greg-ashby** [comment]
I need that as well. Doesn't seem to be a way to override the default behaviour, so I'm currently getting around it by setting the default header row text to "", and appending a second header row where I show column header text. It's not a terrible work around, but requires an extra header row which might not be an option for some design requirements. Would be better to have an option of whether to show the header text beside each checkbox or not (and probably default to not).

**Comment by TatuLund** [comment]
Version 0.96 adds another constructor, which can be used to configure the label. You can have different string for true and false, which is handy for localisation etc.
