### ISSUE TITLE
Error after adding add on into maven

### ISSUE THREAD

**Issue by djerman** [vaadin/grid-renderers-collection-addon#41]
After I add add on into maven and try to compile widgetset (or start app) I got this error: 

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building jpgz 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- vaadin-maven-plugin:8.4.1:update-widgetset (default-cli) @ jpgz ---
[WARNING] GWT plugin is configured to detect modules, but none were found.
[INFO] No widgetsets found - generating AppWidgetset if necessary.
[INFO] Updating widgetset AppWidgetset
[INFO] Adding resource directory to command classpath: /home/djerman/git/jpgz/src/main/resources
[INFO] Adding resource directory to command classpath: /home/djerman/git/jpgz/target/generated-resources/gwt
[INFO] Using com.vaadin:vaadin-client version 8.4.1
[INFO] Using com.vaadin:vaadin-client-compiler version 8.4.1
[INFO] Widgetsets found from classpath:
[INFO] 	org.vaadin.teemu.ratingstars.gwt.RatingStarsWidgetset in jar:file:/home/djerman/.m2/repository/org/vaadin/addons/ratingstars/2.1/ratingstars-2.1.jar!/
[INFO] 	org.vaadin.sparklines.SparklinesWidgetset in jar:file:/home/djerman/.m2/repository/org/vaadin/addons/sparklines/7.0.2/sparklines-7.0.2.jar!/
[INFO] 	org.vaadin.grid.cellrenderers.RenderersCollectionWidgetSet in jar:file:/home/djerman/.m2/repository/com/vaadin/grid-renderers-collection-addon/2.2.10/grid-renderers-collection-addon-2.2.10.jar!/
[INFO] 	com.vaadin.DefaultWidgetSet in jar:file:/home/djerman/.m2/repository/com/vaadin/vaadin-client/8.4.1/vaadin-client-8.4.1.jar!/
[INFO] Addon styles found from classpath:
[INFO] 
[INFO] Search took 21ms
[INFO] 
[INFO] --- vaadin-maven-plugin:8.4.1:compile (default-cli) @ jpgz ---
[INFO] auto discovered modules [AppWidgetset]
[INFO] Using com.vaadin:vaadin-client version 8.4.1
[INFO] Using com.vaadin:vaadin-client-compiler version 8.4.1
[INFO] Compiling module AppWidgetset
[INFO] [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:3997)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.getInternalCompilerException(GwtAstBuilder.java:4404)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.createMembers(GwtAstBuilder.java:4096)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3929)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3971)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:129)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:336)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:470)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1040)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO] Caused by: java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.lookup.MethodBinding.isDefaultMethod()Z
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.createMethod(GwtAstBuilder.java:4191)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.createMembers(GwtAstBuilder.java:4086)
[INFO] 	... 21 more
[INFO]    [ERROR] at DefaultRule_eu.java(22): public class DefaultRule_eu extends DefaultRule
[INFO]       org.eclipse.jdt.internal.compiler.ast.TypeDeclaration
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.081 s
[INFO] Finished at: 2018-05-12T11:19:36+02:00
[INFO] Final Memory: 24M/347M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:8.4.1:compile (default-cli) on project jpgz: Command [[
[ERROR] /bin/sh -c '/usr/lib/jvm/java-8-oracle/jre/bin/java' '-Xmx1G' '-Dgwt.persistentunitcache=false' 'com.google.gwt.dev.Compiler' '-logLevel' 'INFO' '-style' 'OBF' '-war' '/home/djerman/git/jpgz/target/classes/VAADIN/widgetsets' '-localWorkers' '4' '-failOnError' '-XfragmentCount' '-1' '-sourceLevel' 'auto' '-gen' '/home/djerman/git/jpgz/target/.generated' 'AppWidgetset'
[ERROR] ]] failed with status 1
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Same with vaadin 8.3.3

**Comment by djerman** [comment]
Thanks,
Yes, I tried few times with and with out this add on to compile widgeset. Every time without add on no problem no errors, every time with add on I got this error. I have used this with vaadin 7 and there was no errors. 
I have also found few links before I wrote this with similar problem, one of them is a first link you have have posted, but then it makes new error
 com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
just like the one mentioned in your second link and I did just like they said, but now new error

Errors in com/google/gwt/emul/java/util/ConcurrentModificationDetector.java
[ERROR] Line 62: 'ConcurrentModificationDetector.ModCountable' has invalid name '*'.

one lead to another, and so on :)

**Comment by TatuLund** [comment]
That sounds really odd. 

I found one more link with similar issues

https://stackoverflow.com/questions/43739522/vaadin-widgetset-compilation-error-after-vaadin8-migration

**Comment by djerman** [comment]
It was not migration, but I will check this, thanks...

**Comment by djerman** [comment]
It was not migration, but I will check this, thanks...
