### ISSUE TITLE
BooleanSwitchRenderer still usable with grid.setEnabled(false)

### ISSUE THREAD

**Issue by onlineandy** [vaadin/grid-renderers-collection-addon#53]
Version 2.3.2

If I disable the grid (e.g. in org.vaadin.grid.cellrenderers.demo.DemoUI.DateTextDemo) then the checkboxes (and the other widgets like textfield and datefield) looks disabled. But they are usable without firing a changeevent.

So, it is kind of mixed state. I would like to have disabled checkboxes if the whole grid is disabled with setEnabled(false).

**Comment by TatuLund** [comment]
I think this happens with other editable renderers as well, since I have not given much thought to Grid's global enabled/disabled state. But this is straightforward to fix.

**Comment by TatuLund** [comment]
Version 2.3.3 with fix is released in Directory
