### ISSUE TITLE
GWTGraphics not found issue

### ISSUE THREAD

**Issue by arendd** [vaadin/grid-renderers-collection-addon#55]
Hello,

I have a strange issue when using the 'grid-renderers-collection-addon' in a Vaadin project, that used gradle for build management. I created the initial project with the [Vaadin Gradle Plugin](https://github.com/johndevs/gradle-vaadin-plugin). I inserted my code and all dependecies and everything works as expected so far, but then I added the 'grid-renderers-collection-addon', because the [DeleteButtonRenderer](https://github.com/TatuLund/GridFastNavigation/blob/vaadin8/GridFastNavigation-addon/src/main/java/org/vaadin/patrik/DeleteButtonRenderer.java) class is deprecated in the GridFastNavigation addon.

And now I can not execute 'VaadinCompile' anymore and get this error:
**Unable to find 'org/vaadin/gwtgraphics/GWTGraphics.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?**

I tried it within Eclipse and on the console, but I always receive the same issue.
I'm not sure what is the reason, but when I remove the addon from the gradle build file everything is fine. 
So I guess that it is myabe a problem with the 'grid-renderer-collection-addon'!?

Here is the used gradle build file:

``
plugins {
  id 'com.devsoap.plugin.vaadin' version '2.0.0.beta1'
  id 'eclipse-wtp'
}

apply plugin: 'java-library'
apply plugin: 'com.devsoap.plugin.vaadin'
apply plugin: 'war'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories{ 
    jcenter()
}

dependencies {
     compile group: 'org.glassfish.jersey.core', name: 'jersey-client', version:'2.27'
     compile group: 'org.glassfish.jersey.inject', name: 'jersey-hk2', version:'2.27'
     compile group: 'commons-fileupload', name: 'commons-fileupload', version:'1.3.3'
     compile group: 'com.github.scribejava', name: 'scribejava-apis', version:'3.0.0'
     compile group: 'org.json', name: 'json', version:'20180813'
     compile group: 'org.vaadin.patrik', name: 'GridFastNavigation', version:'2.4.3'
     compile group: 'com.vaadin', name: 'grid-renderers-collection-addon', version:'2.3.3'
     compile group: 'org.vaadin.olli', name: 'v8-client-storage', version:'0.1'
     compile group: 'javax.servlet', name: 'javax.servlet-api', version:'3.0.1' 
}

vaadin {
    version '8.4.4' 
    push true
}

vaadinRun {
    server 'jetty'
    serverPort 8080
}
``
Any ideas, what could be the reason?

**Comment by TatuLund** [comment]
This is not actually issue with GridFastNavigation at all

> grid-renderers-collection-addon

This add-on has SparklineRenderer, which uses GWTGraphics. With Maven this transitive dependency works ok. So I really do not know why it does not work with Gradle.

See: https://github.com/vaadin/grid-renderers-collection-addon/blob/vaadin8/grid-renderers-collection-addon/pom.xml#L97

**Comment by arendd** [comment]
You are right. I tested my project with a Maven build configuration and it worked. 
This is really strange ;(  I have no idea why Gradle is unable to resolve the dependency correct...

**Comment by TatuLund** [comment]
> I have no idea why Gradle is unable to resolve the dependency correct...

Me neither, but I have seen similar questions in our Forum with other add-ons and other places (so I know it is not specific issue to this add-on)
